version: '3.7'

services:
  postgres:
    image: postgres:12.3
    init: true
    environment:
      POSTGRES_USER: "1"
      POSTGRES_PASSWORD: "1"
      PGDATA: "/var/lib/postgresql/data/sampleDir"
      POSTGRES_DB: "dev"
    ports:
      - "15432:5432"
#    volumes:
#      - ${PWD}/scripts/postgres:/docker-entrypoint-initdb.d/

  pgadmin:
    image: dpage/pgadmin4
    init: true
    environment:
      PGADMIN_DEFAULT_EMAIL: "1"
      PGADMIN_DEFAULT_PASSWORD: "1"
    ports:
      - "16543:80"
    depends_on:
      - postgres