// Code generated by "stringer -type=TaskState"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Processing-0]
	_ = x[Done-1]
	_ = x[TimedOut-2]
	_ = x[Canceled-3]
}

const _TaskState_name = "ProcessingDoneTimedOutCanceled"

var _TaskState_index = [...]uint8{0, 10, 14, 22, 30}

func (i TaskState) String() string {
	if i < 0 || i >= TaskState(len(_TaskState_index)-1) {
		return "TaskState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TaskState_name[_TaskState_index[i]:_TaskState_index[i+1]]
}
