// Code generated by "stringer -type=taskState"; DO NOT EDIT.

package task

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Processing-0]
	_ = x[Done-1]
	_ = x[TimedOut-2]
	_ = x[Canceled-3]
	_ = x[Aborted-4]
}

const _taskState_name = "ProcessingDoneTimedOutCanceledAborted"

var _taskState_index = [...]uint8{0, 10, 14, 22, 30, 37}

func (i taskState) String() string {
	if i < 0 || i >= taskState(len(_taskState_index)-1) {
		return "taskState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _taskState_name[_taskState_index[i]:_taskState_index[i+1]]
}
